# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/enrollwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnrollWindow(object):
    def setupUi(self, EnrollWindow):
        EnrollWindow.setObjectName("EnrollWindow")
        EnrollWindow.resize(377, 317)
        self.centralwidget = QtWidgets.QWidget(EnrollWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(10, 10, 341, 191))
        self.camera.setObjectName("camera")
        self.pbCapture = QtWidgets.QPushButton(self.centralwidget)
        self.pbCapture.setGeometry(QtCore.QRect(20, 210, 341, 41))
        self.pbCapture.setObjectName("pbCapture")
        EnrollWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EnrollWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 22))
        self.menubar.setObjectName("menubar")
        EnrollWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EnrollWindow)
        self.statusbar.setObjectName("statusbar")
        EnrollWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EnrollWindow)
        QtCore.QMetaObject.connectSlotsByName(EnrollWindow)

    def retranslateUi(self, EnrollWindow):
        _translate = QtCore.QCoreApplication.translate
        EnrollWindow.setWindowTitle(_translate("EnrollWindow", "Enroll User"))
        self.camera.setText(_translate("EnrollWindow", "Camera"))
        self.pbCapture.setText(_translate("EnrollWindow", "Capture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnrollWindow = QtWidgets.QMainWindow()
    ui = Ui_EnrollWindow()
    ui.setupUi(EnrollWindow)
    EnrollWindow.show()
    sys.exit(app.exec_())
