# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbAddUser = QtWidgets.QPushButton(self.centralwidget)
        self.pbAddUser.setGeometry(QtCore.QRect(260, 290, 121, 25))
        self.pbAddUser.setObjectName("pbAddUser")
        self.pbStart = QtWidgets.QPushButton(self.centralwidget)
        self.pbStart.setGeometry(QtCore.QRect(10, 290, 111, 25))
        self.pbStart.setObjectName("pbStart")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(50, 10, 300, 191))
        self.camera.setObjectName("camera")
        self.pbTrain = QtWidgets.QPushButton(self.centralwidget)
        self.pbTrain.setGeometry(QtCore.QRect(130, 290, 121, 25))
        self.pbTrain.setObjectName("pbTrain")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(10, 210, 371, 41))
        self.label_info.setObjectName("label_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMain = QtWidgets.QAction(MainWindow)
        self.actionMain.setObjectName("actionMain")
        self.actionUser = QtWidgets.QAction(MainWindow)
        self.actionUser.setObjectName("actionUser")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition"))
        self.pbAddUser.setText(_translate("MainWindow", "Add User"))
        self.pbStart.setText(_translate("MainWindow", "Start Detection"))
        self.camera.setText(_translate("MainWindow", "Camera"))
        self.pbTrain.setText(_translate("MainWindow", "Re-Train"))
        self.label_info.setText(_translate("MainWindow", "Info"))
        self.actionMain.setText(_translate("MainWindow", "Main"))
        self.actionUser.setText(_translate("MainWindow", "User List"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
