# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/userlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserList(object):
    def setupUi(self, UserList):
        UserList.setObjectName("UserList")
        UserList.resize(403, 325)
        self.centralwidget = QtWidgets.QWidget(UserList)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 361, 201))
        self.listWidget.setObjectName("listWidget")
        self.pbDeleteUser = QtWidgets.QPushButton(self.centralwidget)
        self.pbDeleteUser.setGeometry(QtCore.QRect(20, 240, 121, 25))
        self.pbDeleteUser.setObjectName("pbDeleteUser")
        UserList.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserList)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 22))
        self.menubar.setObjectName("menubar")
        UserList.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserList)
        self.statusbar.setObjectName("statusbar")
        UserList.setStatusBar(self.statusbar)

        self.retranslateUi(UserList)
        QtCore.QMetaObject.connectSlotsByName(UserList)

    def retranslateUi(self, UserList):
        _translate = QtCore.QCoreApplication.translate
        UserList.setWindowTitle(_translate("UserList", "Enrolled User List"))
        self.pbDeleteUser.setText(_translate("UserList", "Delete User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserList = QtWidgets.QMainWindow()
    ui = Ui_UserList()
    ui.setupUi(UserList)
    UserList.show()
    sys.exit(app.exec_())
